# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

  if VAGRANTFILE_API_VERSION == "1"
    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

      config.vm.box = "raring64"

      config.vm.customize ["modifyvm", :id, "--memory", 4096, "--cpus", "4", "--ioapic", "on"]

      config.vm.provision :shell, :path => "bootstrap.sh"
    end
  end

  if VAGRANTFILE_API_VERSION == "2"

    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

      config.vm.box = "raring64"

      config.vm.provider :virtualbox do |vb|
         vb.customize ["modifyvm", :id, "--memory", 4096, "--cpus", "4", "--ioapic", "on"]
      
      config.vm.provision :shell, :path => "bootstrap.sh"
    end

  end

end